#version: '3.8' docker-compose up --build

services:
  web:
    build: .
    command: python web.py
    environment:
      - FLASK_ENV=development
    volumes:
      - ./conf/web.conf:/srv/app/conf/web.conf
      - .:/srv/app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: postgres:16
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    restart: always
    environment:
      - POSTGRES_DB=${db_name}
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_PORT=${db_port}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
        - ":${db_port}:5432"
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${db_user:-user} -d ${db_name:-testdb}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

volumes:
  pgdata:
    driver: local

networks:
  mynetwork:
    external: true